version: "3"

services:
  app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    command: yarn run dev -p 8080
    environment: 
      - NODE_ENV=development
      - NEXT_APP_API_URL=http://localhost:8080/api/
    ports:
      - "8080:8080"
    container_name: app
    working_dir: /usr/app
    volumes:
       - ./next-app:/usr/app
       - "/.git:/usr/app/.git"
    tty: true
    stdin_open: false
  test:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    command: yarn test
    container_name: test
    working_dir: /usr/app
    volumes:
       - ./next-app:/usr/app
       - "/.git:/usr/app/.git"
    tty: true
    stdin_open: false

      